### ISSUE TITLE
Add download links to tools and utilities

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/frc-docs#1086]
Example:
Either the `Installing Software` or `Glass` sections should have a download link for glass.

Going through the wpilib installer or manually traversing artifactory shouldn't be necessary for a 900kb exe.

This probably applies to other wpilib tools too.

**Comment by PeterJohnson** [comment]
Other wpilib tools are very difficult to make standalone, because they are Java applications and need a Java 11 JRE installed.  Glass is easier as a standalone exe, but even it needs the MSVC runtime installed (it's not installed as a part of Windows).  We also don't build releases for our tools--they're all packaged as Maven artifacts.

**Comment by prateekma** [comment]
If we provide a separate standalone Glass download for Mac, we would also need to notarize it

**Comment by Daltz333** [comment]
It's already a pain to debug users custom configurations *with* the installer installed. I don't think we should provide individual installs for users, at least in any sort of a supported sense. It's fine if they find them on their own and know what their doing.

**Comment by Daltz333** [comment]
I believe the decision is to not do this for the meantime. If the process ends up getting streamlined a bit more, we may take a further look at this. I am going to close this issue.
