### ISSUE TITLE
Document the drive classes

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-docs#1109]
It should cover the following:

1. What drive inverse kinematics classes are available (DifferentialDrive, MecanumDrive)
2. What inverse kinematic methods each class provides
3. What RobotDriveBase.setDeadband() does (adds a deadband to joystick values while rescaling the passthrough region so there isn't an output discontinuity; also note that users can square the input or apply other transformations to the input and the deadband will compose with it)
4. What RobotDriveBase.setMaxOutput() does

**Comment by jasondaming** [comment]
This article seems out of place under actuators but I think we can add this stuff to it rather than create a new article.  We really need to rethink the structure of Basic Programming as it is a catchall that is hard to find what you want / need.

https://docs.wpilib.org/en/stable/docs/software/actuators/wpi-drive-classes.html

**Comment by Daltz333** [comment]
Ideally I think this would be in the zero-to-robot step-4 section.

**Comment by jasondaming** [comment]
I think it is important but I disagree.  Zero to Robot gets them running.  This is optimization, I think it is good optimization that teams should do but that is a slippery slope of do we include auto tutorial or a joystick howto or....which are all optimizations.
