### ISSUE TITLE
Remove the `docs` folder

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/frc-docs#1359]
Removing the docs folder and moving its children up a level would make urls shorter and less redundant.

**Comment by Daltz333** [comment]
This doesn't really hurt us, and would be a huge undertaking. Every article would need to be redirected, and this actually might reflect poorly on our SEO (due to massive JS redirects). I also think having the sections nested one level deeper makes the repo a bit nicer for organization of non-doc articles. IE: content is all in /docs/ and contributors could get confused by relating source files (conf.py, redirects, etc).
