### ISSUE TITLE
Document how to include C++ and Java Libraries in robot code

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs#167]
I received this email message.  It seems like something we should include in the documentation.

>Good afternoon,
>I have a question regarding how to include compiled libraries with gradle so they compile during the build process. I am trying to include a .a file while building code in vs code (for a c++ frc project), and we cannot find the correct documentation as to what command to use and where it needs to be. Could you point to where this documentation is for the c++ implementation of gradle?
>Thank you in advance,

**Comment by Daltz333** [comment]
Java it's quite easy, by just including it in the dependencies section.

C++ it's 🤷‍♂

**Comment by calcmogul** [comment]
Assuming the .a file is already in an accessible location, you can add and remove compiler flags like so:
```groovy
nativeUtils.platformConfigs.named("linuxathena").configure {
    it.cppCompiler.args.remove('-g')
}

nativeUtils.platformConfigs.named("linuxx86-64").configure {
    it.cppCompiler.args.remove('-g')
    it.linker.args.add('-lstdc++fs')
}
```

**Comment by calcmogul** [comment]
If a .a isn't available, your only realistic option with the Gradle build system is to copy-paste the library's source into your Git repo. Downsides include:

1. You have to keep a giant ball of mud in each codebase that needs it
2. Getting it to compile may be annoying because our GradleRIO setup isn't the build system the library was originally built with. Extra compilation flags may be needed, etc.
