### ISSUE TITLE
Status lights reference does not print well

### ISSUE THREAD

**Issue by bovlb** [wpilibsuite/frc-docs#1986]
https://github.com/wpilibsuite/frc-docs/blob/main/source/docs/hardware/hardware-basics/status-lights-ref.rst

I find this page to be an invaluable resource.  I print a copy for my CSA binder.  Unfortunately, it does not print well, and section titles are often at the bottom of the previous page.  Would there be any possibility of making a more printable version?  I can't be the only person who is trying to do this.

Minor notes:
* Any plans to add Pigeon 2?  https://store.ctr-electronics.com/content/user-manual/Pigeon2%20User's%20Guide.pdf section 1.5
* Might be worth clarifying in text that the "Talon FX" section applies to Falcon 500s.  This comes up almost every time.

**Comment by Daltz333** [comment]
While we support the PDF build, it's not a primary target of the documentation and there are a large number of issues with it.

See https://github.com/wpilibsuite/frc-docs/issues/211 if you'd like to make a note of this issue on there also, but I don't see it realistically being fixed in the short-term unless an external contributor who is familiar with LaTeX and Sphinx is willing to make the modifications.

My recommendation is for you to screenshot/edit them into a PDF yourself in a PDF editor of your choice in the meantime; it's not a perfect solution, but it'll work. I'm closing this issue, but if you have any questions, feel free to respond here.
