### ISSUE TITLE
Improve debugging page

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#355]
[Debugging a Robot Program](http://frcdocs.wpi.edu/en/latest/docs/software/wpilib-overview/debugging-robot-program.html) talks about setting a breakpoint, but not single stepping.

**Comment by jasondaming** [comment]
I am okay with showing how to launch the debugger and other FRC specific things but I don't think actual VS Code debugging steps should be discussed here.  I would propose that we link to: https://code.visualstudio.com/docs/editor/debugging which has tons of great information but duplicating a similar tutorial here seems of little value.

Even since this was written I already see numerous differences between this and the current version of VS Code.

Once direction is agreed upon here I will try to work on this.

**Comment by Daltz333** [comment]
That direction is fine with me, however, I'd like to overall expand the debugging page to include links to other resources on debugging a java program, even if we don't go over it ourselves. This links should be reliable (no blogs) and free/school safe.
