### ISSUE TITLE
Inconsistant linking of code in Command-Based Programming documentation

### ISSUE THREAD

**Issue by cbennet** [wpilibsuite/frc-docs#691]
For example on the [structuring a command based robot project page](https://docs.wpilib.org/en/stable/docs/software/commandbased/structuring-command-based-project.html) robotcontainer code is only linked to in its section at the middle of the page, never when referenced elsewhere. While on the [binding commands page](https://docs.wpilib.org/en/stable/docs/software/commandbased/binding-commands-to-triggers.html) Trigger and button have the code linked when first mentioned, not in the section about it.

**Comment by jasondaming** [comment]
@Daltz333 what do we want to do here?  It seems like there are a lot of other places in the docs where we could be linking to the the API but don't.  I hate to remove functionality but if I was doing this as a new article I think I would lean towards linking neither.  If we want to retain some linking I guess I would favor linking at the explanation rather than the various examples.

**Comment by Daltz333** [comment]
@cbennet Looking at this, I don't really see any issue with the current implementation. It's sort of added whenever the author feels that its relevant to have a reference.

> For example on the structuring a command based robot project page robotcontainer code is only linked to in its section at the middle of the page, never when referenced elsewhere. 

On this page, it's linked because it's the beginning of an overview of the commandbased robot structure. It's not really necessary and more of a convenience thing. The article doesn't really improve when it's removed.

> While on the binding commands page Trigger and button have the code linked when first mentioned, not in the section about it.

This seems like a non-issue.
