### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by ItayZiv** [wpilibsuite/frc-docs#722]
Not sure if this should even be added or how, but it might be useful to have permalinks to certain articles (For example `docs.wpilib.org/permalinks/????/shuffleboard` would be linked to the index of shuffleboard no matter if it gets moved or renamed in the future).
This could also redirect automatically to the preferred stable/latest version of docs.
An example usage would be https://wpilib.org/ where right now there's a link to a specific page, where renaming or relocation would break the link.

**Comment by Daltz333** [comment]
Version Control has no concept of permanence, so this a problem with version controlled documentation at its root. Using an external service as you suggested would add another layer of maintenance that would quickly become an issue over time. ReadTheDocs does however support redirects which we will use.

We will keep redirects for *one* year, after of which they will be moved and website maintainers will need to update their links. This follows WPILib's feature deprecation policy. 

We can't have permalinks because what happens five years from now. Do we have the following ugly scenario:
2020 -> 2021
2020 -> 2022
2020 -> 2023
...
2021 -> 2025


This quickly is unmaintainable. 

I'm closing this as wontfix. Feel free to comment with additional solutions.

**Comment by TheTripleV** [comment]
The main problem with links breaking due to changes is not website maintainers imo. It is posts on Chief Delphi. Sometimes, I find links in Chief Delphi posts that are broken due to age, and it can be frustrating.

One solution to this I see is to serve the latest stable version of the docs instead of stable.
Ex. `https://docs.wpilib.org/en/stable/docs/software/actuators/index.html` would redirect to `https://docs.wpilib.org/en/2020/docs/software/actuators/index.html`

This way, links won't break as archived stable versions don't change.

**Comment by Daltz333** [comment]
I think the solution to this would be to tag at the end of the season for next year. Then have it force-push each commit to the tag. Then we can just set the version to be "yearly", with a notice that it is out-of-date.

**Comment by prateekma** [comment]
You can easily force-push a tag using GitHub Actions and https://github.com/eine/tip

**Comment by Daltz333** [comment]
![image](https://user-images.githubusercontent.com/10674555/88566518-1f316980-d004-11ea-8186-2d5bb72259d3.png)

**Comment by Daltz333** [comment]
https://github.com/wpilibsuite/sphinxext-rediraffe
