### ISSUE TITLE
Point External Link at Different Location in Compile Time

### ISSUE THREAD

**Issue by ssysm** [wpilibsuite/frc-docs#728]
Include content based on configuration
https://www.sphinx-doc.org/en/master/usage/extensions/ifconfig.html

**Comment by Daltz333** [comment]
Use for API docs.

**Comment by sciencewhiz** [comment]
It would have to be fairly intelligent as the api docs location is in the user's home directory and need different patterns for Windows and Linux/Mac.

**Comment by ItayZiv** [comment]
You can use relative links, since the local docs build is in a neighboring folder to the API docs.
The only consideration is what to do if someone downloads from RTD manually.

**Comment by Daltz333** [comment]
I've done a bit of investigation into this and found a few problems that I've reported to the sphinx team.

``ifconfig`` is not compatible for toctree entries making this not plausible https://github.com/sphinx-doc/sphinx/issues/8451

I'm not worried about supporting from RTD manually for HTML, however, we want to only do this for the downloadable HTML build, so this is a bit harder to configure without breaking the website. I may close this as not-possible due to the builder for the live website and the downloaded HTML being the same.

**Comment by Daltz333** [comment]
If anyone has any ideas? Otherwise I may close this as it's unlikely to get implemented due to it requiring a refactor of Sphinx

**Comment by Daltz333** [comment]
An idea that was given was to run post-processing on ``index.html`` to change it to a relative if it's an offline install. This needs to be done as part of the build pipeline. (Some sort of Sphinx end event?), otherwise it will not work as the installer downloads from RTD.

**Comment by TheTripleV** [comment]
Possible solution:

This solution redirects to the online version if the user has internet access or if they are on the online version of frc-docs. If the user is accessing the local version of frc-docs and they do not have an internet connection, they will be redirected to the local version.

In index.rst:
```diff
- WPILib Java API Docs <https://first.wpi.edu/FRC/roborio/release/docs/java/index.html>
+ WPILib Java API Docs <java-api-docs-placeholder.rst>
```

In java-api-docs-placeholder.rst:
```rst
Title
=====

.. raw:: html

    <script>
        if (window.location.href.includes("docs.wpilib.org") || window.navigator.onLine) {
            window.location.href = "https://first.wpi.edu/FRC/roborio/release/docs/java/index.html";
        } else {
            window.location.href = "path_to_local_api_docs.html"
        }
    </script>

Oops.
```
