### ISSUE TITLE
Document enable/disable functionality for PIDController widget

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-docs#833]
The PIDController widget for SmartDashboard/Shuffleboard has an enabled boolean property that isn't supported by the new PIDController class. While it was very important to be able to disable the old PIDController since it automatically wrote to the motor, it is still helpful to pass the enabled flag to user code for while tuning with LiveWindow.

**Comment by jasondaming** [comment]
I am confused as to what documentation is needed here.  Is it why the boolean went away or how it can be added back? or what?

**Comment by Daltz333** [comment]
The new PIDController is ran via the ``calculate()`` method. We should provide an example of how to replicate the old functionality (enabling/disabling via dashboard) with the new PIDController. This can be done via a simple boolean toggle on the dashboard.

There are options that we have discussed and decided against:
- Duplicate PIDController Widgets (One for New PIDController and One for Old PIDController)
  - We aren't necessarily against this, but it really requires someone to open a PR in Shuffleboard, Smartdashboard, and WPILib providing a way to expose whether its a new PIDController or old PIDController, so it's non-trivial.
- Bring back the "enable" boolean, we decided against this as it violates the design of the new pidcontroller as being periodic and continuous.

I don't completely remember on the decision making for this as it was in one of our meetings several months back, so @calcmogul may be able to weigh in a bit more.

This issue is open to document replicating the enable/disable functionality via a NT boolean toggle box.
